### ISSUE TITLE
Could I cut the whole box in the fg picture and put it in to the bg picture?

### ISSUE THREAD

**Issue by ShihuaiXu** [TheDenk/augmixations#1]
Thansk for your great work!
I want to cut the whole box in the fg and put it in to the bg picture, would mind give me some suggestion? The example is shown in below.
I put the pictures in my youdao note, please visit
http://note.youdao.com/s/XDgG6fqO

**Comment by TheDenk** [comment]
Hi @ShihuaiXu , thanks for using augmixations.
Probably I didn't understand the question correctly. 
Yes, u can cut the whole fg image and put in to the bg image. But If your bg image size as the same as fg image size, you just replace bg image.
Also you can use detail config for cut and put images i wrote there: https://github.com/TheDenk/augmixations/wiki/Cutmix-Advanced-Usage. For cut whole fg image just set max_min_h and max_min_w parameters the same as the fg image size.

I hope my answer will help you. Please let me know if you encounter any problems.

**Comment by ShihuaiXu** [comment]
Thanks

**Comment by ShihuaiXu** [comment]
thanks for your help
